import os
open = os.system
while True:
	for i in open:
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
		open("open https://google.com/")
	print(i)