elements =[
   {
      "symbol":"H",
      "name":"Hydrogen",
      "atomic_number":1,
      "atomic_weight":1.00794,
      "electron_configuration":"1s¹",
      "category":"Nonmetal",
      "standard_state":"Gas",
      "boiling_point":"-252.87°C",
      "melting_point":"-259.16°C"
   },
   {
      "symbol":"He",
      "name":"Helium",
      "atomic_number":2,
      "atomic_weight":4.002602,
      "electron_configuration":"1s²",
      "category":"Noble Gas",
      "standard_state":"Gas",
      "boiling_point":"-268.93°C",
      "melting_point":"-272.2°C"
   },
   {
      "symbol":"Li",
      "name":"Lithium",
      "atomic_number":3,
      "atomic_weight":6.939,
      "electron_configuration":"[He] 2s¹",
      "category":"Alkali Metal",
      "standard_state":"Solid",
      "boiling_point":"1342°C",
      "melting_point":"180.54°C"
   },
   {
      "symbol":"Be",
      "name":"Beryllium",
      "atomic_number":4,
      "atomic_weight":9.0121831,
      "electron_configuration":"[He] 2s²",
      "category":"Alkaline Earth Metal",
      "standard_state":"Solid",
      "boiling_point":"2970°C",
      "melting_point":"1287°C"
   },
   {
      "symbol":"B",
      "name":"Boron",
      "atomic_number":5,
      "atomic_weight":10.806,
      "electron_configuration":"[He] 2s² 2p¹",
      "category":"Metalloid",
      "standard_state":"Solid",
      "boiling_point":"3927°C",
      "melting_point":"2075°C"
   },
   {
      "symbol":"C",
      "name":"Carbon",
      "atomic_number":6,
      "atomic_weight":12.011,
      "electron_configuration":"[He] 2s² 2p²",
      "category":"Nonmetal",
      "standard_state":"Solid",
      "boiling_point":"3915°C",
      "melting_point":"3915°C"
   },
   {
      "symbol":"N",
      "name":"Nitrogen",
      "atomic_number":7,
      "atomic_weight":14.007,
      "electron_configuration":"[He] 2s² 2p³",
      "category":"Nonmetal",
      "standard_state":"Gas",
      "boiling_point":"-196°C",
      "melting_point":"-210°C"
   },
   {
      "symbol":"O",
      "name":"Oxygen",
      "atomic_number":8,
      "atomic_weight":15.999,
      "electron_configuration":"[He] 2s² 2p⁴",
      "category":"Nonmetal",
      "standard_state":"Gas",
      "boiling_point":"-183°C",
      "melting_point":"-219°C"
   },
   {
      "symbol":"F",
      "name":"Fluorine",
      "atomic_number":9,
      "atomic_weight":18.998403163,
      "electron_configuration":"[He] 2s² 2p⁵",
      "category":"Halogen",
      "standard_state":"Gas",
      "boiling_point":"-188°C",
      "melting_point":"-220°C"
   },
   {
      "symbol":"Ne",
      "name":"Neon",
      "atomic_number":10,
      "atomic_weight":20.1797,
      "electron_configuration":"[He] 2s² 2p⁶",
      "category":"Noble Gas",
      "standard_state":"Gas",
      "boiling_point":"-246°C",
      "melting_point":"-248.6°C"
   },
   {
      "symbol":"Na",
      "name":"Sodium",
      "atomic_number":11,
      "atomic_weight":22.98976928,
      "electron_configuration":"[Ne] 3s¹",
      "category":"Alkali Metal",
      "standard_state":"Solid",
      "boiling_point":"883°C",
      "melting_point":"97.8°C"
   },
   {
      "symbol":"Mg",
      "name":"Magnesium",
      "atomic_number":12,
      "atomic_weight":24.305,
      "electron_configuration":"[Ne] 3s²",
      "category":"Alkaline Earth Metal",
      "standard_state":"Solid",
      "boiling_point":"1090°C",
      "melting_point":"650°C"
   },
   {
      "symbol":"Al",
      "name":"Aluminium",
      "atomic_number":13,
      "atomic_weight":26.9815385,
      "electron_configuration":"[Ne] 3s² 3p¹",
      "category":"Metal",
      "standard_state":"Solid",
      "boiling_point":"2519°C",
      "melting_point":"660.32°C"
   },
   {
      "symbol":"Si",
      "name":"Silicon",
      "atomic_number":14,
      "atomic_weight":28.085,
      "electron_configuration":"[Ne] 3s² 3p²",
      "category":"Metalloid",
      "standard_state":"Solid",
      "boiling_point":"3265°C",
      "melting_point":"1414°C"
   },
   {
      "symbol":"P",
      "name":"Phosphorus",
      "atomic_number":15,
      "atomic_weight":30.973762,
      "electron_configuration":"[Ne] 3s² 3p³",
      "category":"Nonmetal",
      "standard_state":"Solid",
      "boiling_point":"280°C",
      "melting_point":"44.15°C"
   },
   {
      "symbol":"S",
      "name":"Sulfur",
      "atomic_number":16,
      "atomic_weight":32.06,
      "electron_configuration":"[Ne] 3s² 3p⁴",
      "category":"Nonmetal",
      "standard_state":"Solid",
      "boiling_point":"444.67°C",
      "melting_point":"115.21°C"
   },
   {
      "symbol":"Cl",
      "name":"Chlorine",
      "atomic_number":17,
      "atomic_weight":35.453,
      "electron_configuration":"[Ne] 3s² 3p⁵",
      "category":"Halogen",
      "standard_state":"Gas",
      "boiling_point":"-34.04°C",
      "melting_point":"-101.5°C"
   },
   {
      "symbol":"Ar",
      "name":"Argon",
      "atomic_number":18,
      "atomic_weight":39.948,
      "electron_configuration":"[Ne] 3s² 3p⁶",
      "category":"Noble Gas",
      "standard_state":"Gas",
      "boiling_point":"-185.87°C",
      "melting_point":"-189.34°C"
   },
   {
      "symbol":"K",
      "name":"Potassium",
      "atomic_number":19,
      "atomic_weight":39.0983,
      "electron_configuration":"[Ar] 4s¹",
      "category":"Alkali Metal",
      "standard_state":"Solid",
      "boiling_point":"759°C",
      "melting_point":"63.38°C"
   },
   {
      "symbol":"Ca",
      "name":"Calcium",
      "atomic_number":20,
      "atomic_weight":40.078,
      "electron_configuration":"[Ar] 4s²",
      "category":"Alkaline Earth Metal",
      "standard_state":"Solid",
      "boiling_point":"1484°C",
      "melting_point":"842°C"
   },
   {
      "symbol":"Sc",
      "name":"Scandium",
      "atomic_number":21,
      "atomic_weight":44.955908,
      "electron_configuration":"[Ar] 3d¹ 4s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"2836°C",
      "melting_point":"1541°C"
   },
   {
      "symbol":"Ti",
      "name":"Titanium",
      "atomic_number":22,
      "atomic_weight":47.867,
      "electron_configuration":"[Ar] 3d² 4s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"3287°C",
      "melting_point":"1668°C"
   },
   {
      "symbol":"V",
      "name":"Vanadium",
      "atomic_number":23,
      "atomic_weight":50.9415,
      "electron_configuration":"[Ar] 3d³ 4s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"3407°C",
      "melting_point":"1910°C"
   },
   {
      "symbol":"Cr",
      "name":"Chromium",
      "atomic_number":24,
      "atomic_weight":51.9961,
      "electron_configuration":"[Ar] 3d⁴ 4s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"2671°C",
      "melting_point":"1907°C"
   },
   {
      "symbol":"Mn",
      "name":"Manganese",
      "atomic_number":25,
      "atomic_weight":54.938044,
      "electron_configuration":"[Ar] 3d⁵ 4s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"1962°C",
      "melting_point":"1246°C"
   },
   {
      "symbol":"Fe",
      "name":"Iron",
      "atomic_number":26,
      "atomic_weight":55.845,
      "electron_configuration":"[Ar] 3d⁶ 4s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"2861°C",
      "melting_point":"1538°C"
   },
   {
      "symbol":"Co",
      "name":"Cobalt",
      "atomic_number":27,
      "atomic_weight":58.933194,
      "electron_configuration":"[Ar] 3d⁷ 4s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"2927°C",
      "melting_point":"1495°C"
   },
   {
      "symbol":"Ni",
      "name":"Nickel",
      "atomic_number":28,
      "atomic_weight":58.6934,
      "electron_configuration":"[Ar] 3d⁸ 4s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"2732°C",
      "melting_point":"1453°C"
   },
   {
      "symbol":"Cu",
      "name":"Copper",
      "atomic_number":29,
      "atomic_weight":63.546,
      "electron_configuration":"[Ar] 3d¹⁰ 4s¹",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"2567°C",
      "melting_point":"1083°C"
   },
   {
      "symbol":"Zn",
      "name":"Zinc",
      "atomic_number":30,
      "atomic_weight":65.38,
      "electron_configuration":"[Ar] 3d¹⁰ 4s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"907°C",
      "melting_point":"419.58°C"
   },
   {
      "symbol":"Ga",
      "name":"Gallium",
      "atomic_number":31,
      "atomic_weight":69.723,
      "electron_configuration":"[Ar] 3d¹⁰ 4s² 4p¹",
      "category":"Metal",
      "standard_state":"Solid",
      "boiling_point":"2673°C",
      "melting_point":"29.76°C"
   },
   {
      "symbol":"Ge",
      "name":"Germanium",
      "atomic_number":32,
      "atomic_weight":72.63,
      "electron_configuration":"[Ar] 3d¹⁰ 4s² 4p²",
      "category":"Metalloid",
      "standard_state":"Solid",
      "boiling_point":"2830°C",
      "melting_point":"938.25°C"
   },
   {
      "symbol":"As",
      "name":"Arsenic",
      "atomic_number":33,
      "atomic_weight":74.922,
      "electron_configuration":"[Ar] 3d¹⁰ 4s² 4p³",
      "category":"Metalloid",
      "standard_state":"Solid",
      "boiling_point":"613°C",
      "melting_point":"817°C"
   },
   {
      "symbol":"Se",
      "name":"Selenium",
      "atomic_number":34,
      "atomic_weight":78.96,
      "electron_configuration":"[Ar] 3d¹⁰ 4s² 4p⁴",
      "category":"Nonmetal",
      "standard_state":"Solid",
      "boiling_point":"685°C",
      "melting_point":"221°C"
   },
   {
      "symbol":"Br",
      "name":"Bromine",
      "atomic_number":35,
      "atomic_weight":79.904,
      "electron_configuration":"[Ar] 3d¹⁰ 4s² 4p⁵",
      "category":"Halogen",
      "standard_state":"Liquid",
      "boiling_point":"58.8°C",
      "melting_point":"-7.3°C"
   },
   {
      "symbol":"Kr",
      "name":"Krypton",
      "atomic_number":36,
      "atomic_weight":83.798,
      "electron_configuration":"[Ar] 3d¹⁰ 4s² 4p⁶",
      "category":"Noble Gas",
      "standard_state":"Gas",
      "boiling_point":"-153.22°C",
      "melting_point":"-157.36°C"
   },
   {
      "symbol":"Rb",
      "name":"Rubidium",
      "atomic_number":37,
      "atomic_weight":85.468,
      "electron_configuration":"[Kr] 5s¹",
      "category":"Alkali Metal",
      "standard_state":"Solid",
      "boiling_point":"686°C",
      "melting_point":"39.31°C"
   },
   {
      "symbol":"Sr",
      "name":"Strontium",
      "atomic_number":38,
      "atomic_weight":87.62,
      "electron_configuration":"[Kr] 5s²",
      "category":"Alkaline Earth Metal",
      "standard_state":"Solid",
      "boiling_point":"1657°C",
      "melting_point":"777°C"
   },
   {
      "symbol":"Y",
      "name":"Yttrium",
      "atomic_number":39,
      "atomic_weight":88.90584,
      "electron_configuration":"[Kr] 4d¹ 5s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"3611°C",
      "melting_point":"1526°C"
   },
   {
      "symbol":"Zr",
      "name":"Zirconium",
      "atomic_number":40,
      "atomic_weight":91.224,
      "electron_configuration":"[Kr] 4d² 5s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"4682°C",
      "melting_point":"1855°C"
   },
   {
      "symbol":"Nb",
      "name":"Niobium",
      "atomic_number":41,
      "atomic_weight":92.90637,
      "electron_configuration":"[Kr] 4d⁴ 5s¹",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"5017°C",
      "melting_point":"2468°C"
   },
   {
      "symbol":"Mo",
      "name":"Molybdenum",
      "atomic_number":42,
      "atomic_weight":95.95,
      "electron_configuration":"[Kr] 4d⁵ 5s¹",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"4612°C",
      "melting_point":"2617°C"
   },
   {
      "symbol":"Tc",
      "name":"Technetium",
      "atomic_number":43,
      "atomic_weight":98,
      "electron_configuration":"[Kr] 4d⁵ 5s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"4265°C",
      "melting_point":"2157°C"
   },
   {
      "symbol":"Ru",
      "name":"Ruthenium",
      "atomic_number":44,
      "atomic_weight":101.1,
      "electron_configuration":"[Kr] 4d⁷ 5s¹",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"3900°C",
      "melting_point":"2334°C"
   },
   {
      "symbol":"Rh",
      "name":"Rhodium",
      "atomic_number":45,
      "atomic_weight":102.9,
      "electron_configuration":"[Kr] 4d⁸ 5s¹",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"3727°C",
      "melting_point":"1966°C"
   },
   {
      "symbol":"Pd",
      "name":"Palladium",
      "atomic_number":46,
      "atomic_weight":106.4,
      "electron_configuration":"[Kr] 4d¹⁰",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"2970°C",
      "melting_point":"1555°C"
   },
   {
      "symbol":"Ag",
      "name":"Silver",
      "atomic_number":47,
      "atomic_weight":107.9,
      "electron_configuration":"[Kr] 4d¹⁰ 5s¹",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"2162°C",
      "melting_point":"961.78°C"
   },
   {
      "symbol":"Cd",
      "name":"Cadmium",
      "atomic_number":48,
      "atomic_weight":112.4,
      "electron_configuration":"[Kr] 4d¹⁰ 5s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"767°C",
      "melting_point":"321.07°C"
   },
   {
      "symbol":"In",
      "name":"Indium",
      "atomic_number":49,
      "atomic_weight":114.8,
      "electron_configuration":"[Kr] 4d¹⁰ 5s² 5p¹",
      "category":"Metal",
      "standard_state":"Solid",
      "boiling_point":"2080°C",
      "melting_point":"156.6°C"
   },
   {
      "symbol":"Sn",
      "name":"Tin",
      "atomic_number":50,
      "atomic_weight":118.7,
      "electron_configuration":"[Kr] 4d¹⁰ 5s² 5p²",
      "category":"Metal",
      "standard_state":"Solid",
      "boiling_point":"2270°C",
      "melting_point":"231.93°C"
   },
   {
      "symbol":"Sb",
      "name":"Antimony",
      "atomic_number":51,
      "atomic_weight":121.8,
      "electron_configuration":"[Kr] 4d¹⁰ 5s² 5p³",
      "category":"Metalloid",
      "standard_state":"Solid",
      "boiling_point":"1587°C",
      "melting_point":"630.63°C"
   },
   {
      "symbol":"Te",
      "name":"Tellurium",
      "atomic_number":52,
      "atomic_weight":127.6,
      "electron_configuration":"[Kr] 4d¹⁰ 5s² 5p⁴",
      "category":"Metalloid",
      "standard_state":"Solid",
      "boiling_point":"988°C",
      "melting_point":"449.51°C"
   },
   {
      "symbol":"I",
      "name":"Iodine",
      "atomic_number":53,
      "atomic_weight":126.9,
      "electron_configuration":"[Kr] 4d¹⁰ 5s² 5p⁵",
      "category":"Halogen",
      "standard_state":"Solid",
      "boiling_point":"184°C",
      "melting_point":"113.7°C"
   },
   {
      "symbol":"Xe",
      "name":"Xenon",
      "atomic_number":54,
      "atomic_weight":131.3,
      "electron_configuration":"[Kr] 4d¹⁰ 5s² 5p⁶",
      "category":"Noble Gas",
      "standard_state":"Gas",
      "boiling_point":"-108.12°C",
      "melting_point":"-111.76°C"
   },
   {
      "symbol":"Cs",
      "name":"Cesium",
      "atomic_number":55,
      "atomic_weight":132.9,
      "electron_configuration":"[Xe] 6s¹",
      "category":"Alkali Metal",
      "standard_state":"Solid",
      "boiling_point":"671°C",
      "melting_point":"28.4°C"
   },
   {
      "symbol":"Ba",
      "name":"Barium",
      "atomic_number":56,
      "atomic_weight":137.3,
      "electron_configuration":"[Xe] 6s²",
      "category":"Alkaline Earth Metal",
      "standard_state":"Solid",
      "boiling_point":"1640°C",
      "melting_point":"727°C"
   },
   {
      "symbol":"La",
      "name":"Lanthanum",
      "atomic_number":57,
      "atomic_weight":138.9,
      "electron_configuration":"[Xe] 5d¹ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"3464°C",
      "melting_point":"918°C"
   },
   {
      "symbol":"Ce",
      "name":"Cerium",
      "atomic_number":58,
      "atomic_weight":140.1,
      "electron_configuration":"[Xe] 4f¹ 5d¹ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"3246°C",
      "melting_point":"798°C"
   },
   {
      "symbol":"Pr",
      "name":"Praseodymium",
      "atomic_number":59,
      "atomic_weight":140.9,
      "electron_configuration":"[Xe] 4f³ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"3785°C",
      "melting_point":"931°C"
   },
   {
      "symbol":"Nd",
      "name":"Neodymium",
      "atomic_number":60,
      "atomic_weight":144.2,
      "electron_configuration":"[Xe] 4f⁴ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"3347°C",
      "melting_point":"1021°C"
   },
   {
      "symbol":"Pm",
      "name":"Promethium",
      "atomic_number":61,
      "atomic_weight":145,
      "electron_configuration":"[Xe] 4f⁵ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"3273°C",
      "melting_point":"1042°C"
   },
   {
      "symbol":"Sm",
      "name":"Samarium",
      "atomic_number":62,
      "atomic_weight":150.4,
      "electron_configuration":"[Xe] 4f⁶ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"2067°C",
      "melting_point":"1072°C"
   },
   {
      "symbol":"Eu",
      "name":"Europium",
      "atomic_number":63,
      "atomic_weight":152,
      "electron_configuration":"[Xe] 4f⁷ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"1529°C",
      "melting_point":"822°C"
   },
   {
      "symbol":"Gd",
      "name":"Gadolinium",
      "atomic_number":64,
      "atomic_weight":157.3,
      "electron_configuration":"[Xe] 4f⁷ 5d¹ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"3273°C",
      "melting_point":"1312°C"
   },
   {
      "symbol":"Tb",
      "name":"Terbium",
      "atomic_number":65,
      "atomic_weight":158.9,
      "electron_configuration":"[Xe] 4f⁹ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"3123°C",
      "melting_point":"1360°C"
   },
   {
      "symbol":"Dy",
      "name":"Dysprosium",
      "atomic_number":66,
      "atomic_weight":162.5,
      "electron_configuration":"[Xe] 4f¹⁰ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"2567°C",
      "melting_point":"1412°C"
   },
   {
      "symbol":"Ho",
      "name":"Holmium",
      "atomic_number":67,
      "atomic_weight":164.9,
      "electron_configuration":"[Xe] 4f¹¹ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"2650°C",
      "melting_point":"1470°C"
   },
   {
      "symbol":"Er",
      "name":"Erbium",
      "atomic_number":68,
      "atomic_weight":167.3,
      "electron_configuration":"[Xe] 4f¹² 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"2510°C",
      "melting_point":"1522°C"
   },
   {
      "symbol":"Tm",
      "name":"Thulium",
      "atomic_number":69,
      "atomic_weight":168.9,
      "electron_configuration":"[Xe] 4f¹³ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"2213°C",
      "melting_point":"1545°C"
   },
   {
      "symbol":"Yb",
      "name":"Ytterbium",
      "atomic_number":70,
      "atomic_weight":173.1,
      "electron_configuration":"[Xe] 4f¹⁴ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"1469°C",
      "melting_point":"824°C"
   },
   {
      "symbol":"Lu",
      "name":"Lutetium",
      "atomic_number":71,
      "atomic_weight":175,
      "electron_configuration":"[Xe] 4f¹⁴ 5d¹ 6s²",
      "category":"Lanthanide",
      "standard_state":"Solid",
      "boiling_point":"3668°C",
      "melting_point":"1663°C"
   },
   {
      "symbol":"Hf",
      "name":"Hafnium",
      "atomic_number":72,
      "atomic_weight":178.5,
      "electron_configuration":"[Xe] 4f¹⁴ 5d² 6s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"4876°C",
      "melting_point":"2233°C"
   },
   {
      "symbol":"Ta",
      "name":"Tantalum",
      "atomic_number":73,
      "atomic_weight":180.9,
      "electron_configuration":"[Xe] 4f¹⁴ 5d³ 6s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"5425°C",
      "melting_point":"3017°C"
   },
   {
      "symbol":"W",
      "name":"Tungsten",
      "atomic_number":74,
      "atomic_weight":183.8,
      "electron_configuration":"[Xe] 4f¹⁴ 5d⁴ 6s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"5930°C",
      "melting_point":"3422°C"
   },
   {
      "symbol":"Re",
      "name":"Rhenium",
      "atomic_number":75,
      "atomic_weight":186.2,
      "electron_configuration":"[Xe] 4f¹⁴ 5d⁵ 6s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"5869°C",
      "melting_point":"3186°C"
   },
   {
      "symbol":"Os",
      "name":"Osmium",
      "atomic_number":76,
      "atomic_weight":190.2,
      "electron_configuration":"[Xe] 4f¹⁴ 5d⁶ 6s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"5300°C",
      "melting_point":"3033°C"
   },
   {
      "symbol":"Ir",
      "name":"Iridium",
      "atomic_number":77,
      "atomic_weight":192.2,
      "electron_configuration":"[Xe] 4f¹⁴ 5d⁷ 6s²",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"4700°C",
      "melting_point":"2446°C"
   },
   {
      "symbol":"Pt",
      "name":"Platinum",
      "atomic_number":78,
      "atomic_weight":195.1,
      "electron_configuration":"[Xe] 4f¹⁴ 5d⁹ 6s¹",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"4100°C",
      "melting_point":"1768°C"
   },
   {
      "symbol":"Au",
      "name":"Gold",
      "atomic_number":79,
      "atomic_weight":197,
      "electron_configuration":"[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
      "category":"Transition Metal",
      "standard_state":"Solid",
      "boiling_point":"3080°C",
      "melting_point":"1064°C"
   },
   {
      "symbol":"Hg",
      "name":"Mercury",
      "atomic_number":80,
      "atomic_weight":200.6,
      "electron_configuration":"[Xe] 4f¹⁴ 5d¹⁰ 6s²",
      "category":"Transition Metal",
      "standard_state":"Liquid",
      "boiling_point":"356°C",
      "melting_point":"-38.83°C"
   },
   {
      "symbol":"Tl",
      "name":"Thallium",
      "atomic_number":81,
      "atomic_weight":204.4,
      "electron_configuration":"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
      "category":"Metal",
      "standard_state":"Solid",
      "boiling_point":"1457°C",
      "melting_point":"304°C"
   },
   {
      "symbol":"Pb",
      "name":"Lead",
      "atomic_number":82,
      "atomic_weight":207.2,
      "electron_configuration":"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
      "category":"Metal",
      "standard_state":"Solid",
      "boiling_point":"1740°C",
      "melting_point":"327.5°C"
   },
   {
      "symbol":"Bi",
      "name":"Bismuth",
      "atomic_number":83,
      "atomic_weight":208.9,
      "electron_configuration":"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
      "category":"Metal",
      "standard_state":"Solid",
      "boiling_point":"1560°C",
      "melting_point":"271.4°C"
   },
   {
      "symbol":"Po",
      "name":"Polonium",
      "atomic_number":84,
      "atomic_weight":209,
      "electron_configuration":"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
      "category":"Metalloid",
      "standard_state":"Solid",
      "boiling_point":"962°C",
      "melting_point":"254°C"
   },
   {
      "symbol":"At",
      "name":"Astatine",
      "atomic_number":85,
      "atomic_weight":210,
      "electron_configuration":"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
      "category":"Halogen",
      "standard_state":"Solid",
      "boiling_point":"337°C",
      "melting_point":"302°C"
   },
   {
      "symbol":"Rn",
      "name":"Radon",
      "atomic_number":86,
      "atomic_weight":222,
      "electron_configuration":"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
      "category":"Noble Gas",
      "standard_state":"Gas",
      "boiling_point":"-61.8°C",
      "melting_point":"-71°C"
   },
   {
      "symbol":"Fr",
      "name":"Francium",
      "atomic_number":87,
      "atomic_weight":223,
      "electron_configuration":"[Rn] 7s¹",
      "category":"Alkali Metal",
      "standard_state":"Solid",
      "boiling_point":"677°C",
      "melting_point":"80.1°C"
   },
   {
      "symbol":"Ra",
      "name":"Radium",
      "atomic_number":88,
      "atomic_weight":226,
      "electron_configuration":"[Rn] 7s²",
      "category":"Alkaline Earth Metal",
      "standard_state":"Solid",
      "boiling_point":"1737°C",
      "melting_point":"696°C"
   },
   {
      "symbol":"Ac",
      "name":"Actinium",
      "atomic_number":89,
      "atomic_weight":227,
      "electron_configuration":"[Rn] 6d¹ 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"3503°C",
      "melting_point":"1050°C"
   },
   {
      "symbol":"Th",
      "name":"Thorium",
      "atomic_number":90,
      "atomic_weight":232.0,
      "electron_configuration":"[Rn] 6d² 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"5061°C",
      "melting_point":"1750°C"
   },
   {
      "symbol":"Pa",
      "name":"Protactinium",
      "atomic_number":91,
      "atomic_weight":231,
      "electron_configuration":"[Rn] 5f² 6d¹ 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"4300°C",
      "melting_point":"1572°C"
   },
   {
      "symbol":"Th",
      "name":"Thorium",
      "atomic_number":90,
      "atomic_weight":232.0,
      "electron_configuration":"[Rn] 6d² 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"5061°C",
      "melting_point":"1750°C"
   },
   {
      "symbol":"U",
      "name":"Uranium",
      "atomic_number":92,
      "atomic_weight":238.0,
      "electron_configuration":"[Rn] 5f³ 6d¹ 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"4131°C",
      "melting_point":"1132°C"
   },
   {
      "symbol":"Np",
      "name":"Neptunium",
      "atomic_number":93,
      "atomic_weight":237,
      "electron_configuration":"[Rn] 5f⁴ 6d¹ 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"3902°C",
      "melting_point":"639°C"
   },
   {
      "symbol":"Pu",
      "name":"Plutonium",
      "atomic_number":94,
      "atomic_weight":244,
      "electron_configuration":"[Rn] 5f⁶ 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"3228°C",
      "melting_point":"639.4°C"
   },
   {
      "symbol":"Am",
      "name":"Americium",
      "atomic_number":95,
      "atomic_weight":243,
      "electron_configuration":"[Rn] 5f⁷ 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"2607°C",
      "melting_point":"994°C"
   },
   {
      "symbol":"Cm",
      "name":"Curium",
      "atomic_number":96,
      "atomic_weight":247,
      "electron_configuration":"[Rn] 5f⁷ 6d¹ 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"3140°C",
      "melting_point":"1340°C"
   },
   {
      "symbol":"Bk",
      "name":"Berkelium",
      "atomic_number":97,
      "atomic_weight":247,
      "electron_configuration":"[Rn] 5f⁹ 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"1050°C",
      "melting_point":"986°C"
   },
   {
      "symbol":"Cf",
      "name":"Californium",
      "atomic_number":98,
      "atomic_weight":251,
      "electron_configuration":"[Rn] 5f¹⁰ 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"900°C",
      "melting_point":"900°C"
   },
   {
      "symbol":"Es",
      "name":"Einsteinium",
      "atomic_number":99,
      "atomic_weight":252,
      "electron_configuration":"[Rn] 5f¹¹ 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Fm",
      "name":"Fermium",
      "atomic_number":100,
      "atomic_weight":257,
      "electron_configuration":"[Rn] 5f¹² 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Md",
      "name":"Mendelevium",
      "atomic_number":101,
      "atomic_weight":258,
      "electron_configuration":"[Rn] 5f¹³ 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"No",
      "name":"Nobelium",
      "atomic_number":102,
      "atomic_weight":259,
      "electron_configuration":"[Rn] 5f¹⁴ 7s²",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Lr",
      "name":"Lawrencium",
      "atomic_number":103,
      "atomic_weight":266,
      "electron_configuration":"[Rn] 5f¹⁴ 7s² 7p¹",
      "category":"Actinide",
      "standard_state":"Solid",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Rf",
      "name":"Rutherfordium",
      "atomic_number":104,
      "atomic_weight":267,
      "electron_configuration":"[Rn] 5f¹⁴ 6d² 7s²",
      "category":"Transition Metal",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Db",
      "name":"Dubnium",
      "atomic_number":105,
      "atomic_weight":270,
      "electron_configuration":"[Rn] 5f¹⁴ 6d³ 7s²",
      "category":"Transition Metal",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Sg",
      "name":"Seaborgium",
      "atomic_number":106,
      "atomic_weight":271,
      "electron_configuration":"[Rn] 5f¹⁴ 6d⁴ 7s²",
      "category":"Transition Metal",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Bh",
      "name":"Bohrium",
      "atomic_number":107,
      "atomic_weight":270,
      "electron_configuration":"[Rn] 5f¹⁴ 6d⁵ 7s²",
      "category":"Transition Metal",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Hs",
      "name":"Hassium",
      "atomic_number":108,
      "atomic_weight":277,
      "electron_configuration":"[Rn] 5f¹⁴ 6d⁶ 7s²",
      "category":"Transition Metal",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Mt",
      "name":"Meitnerium",
      "atomic_number":109,
      "atomic_weight":276,
      "electron_configuration":"[Rn] 5f¹⁴ 6d⁷ 7s²",
      "category":"Transition Metal",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Ds",
      "name":"Darmstadtium",
      "atomic_number":110,
      "atomic_weight":281,
      "electron_configuration":"[Rn] 5f¹⁴ 6d⁸ 7s²",
      "category":"Transition Metal",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Rg",
      "name":"Roentgenium",
      "atomic_number":111,
      "atomic_weight":280,
      "electron_configuration":"[Rn] 5f¹⁴ 6d⁹ 7s²",
      "category":"Transition Metal",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Cn",
      "name":"Copernicium",
      "atomic_number":112,
      "atomic_weight":285,
      "electron_configuration":"[Rn] 5f¹⁴ 6d¹⁰ 7s²",
      "category":"Transition Metal",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Nh",
      "name":"Nihonium",
      "atomic_number":113,
      "atomic_weight":284,
      "electron_configuration":"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
      "category":"unknown",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Fl",
      "name":"Flerovium",
      "atomic_number":114,
      "atomic_weight":289,
      "electron_configuration":"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
      "category":"unknown",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Mc",
      "name":"Moscovium",
      "atomic_number":115,
      "atomic_weight":288,
      "electron_configuration":"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
      "category":"unknown",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Lv",
      "name":"Livermorium",
      "atomic_number":116,
      "atomic_weight":292,
      "electron_configuration":"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
      "category":"unknown",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Ts",
      "name":"Tennessine",
      "atomic_number":117,
      "atomic_weight":294,
      "electron_configuration":"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
      "category":"unknown",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   },
   {
      "symbol":"Og",
      "name":"Oganesson",
      "atomic_number":118,
      "atomic_weight":294,
      "electron_configuration":"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
      "melting_point":"unkown",
      "boiling_point":"unkown",
      "category":"Noble Gas",
      "standard_state":"unknown",
      "boiling_point":"unknown",
      "melting_point":"unknown"
   }
]